# shopify.app.toml
name = "Custom Text Field App"
client_id = "ef270783ca1996cfb7dad3912f8355a6"  # Replace with your API key

[requirements]
api_version = "2025-10"

[webhooks]
# No webhooks needed for this

[access_scopes]
scopes = "read_products"
